### ISSUE TITLE
Keywords for build commands and pre/post copy commands

### ISSUE THREAD

**Issue by WildCard65** [JulienKluge/Spedit#10]
Mind adding pre/post copy commands and some keywords for them(like {current_file}) to make configurating more User Friendly?

**Comment by JulienKluge** [comment]
Can you explain this a little bit more in detail whatyou've ment?

Spedit already has Pre/Post-Commandlines and a distinguishing between files for their own configs will be extremly confusing cause multiple files are allowed to compile and with that multiple configs have to be loaded then and that lead to extremly confusing results inmy opinion.

**Comment by WildCard65** [comment]
the keywords bit is things like {current_file} which gets replaced with path to current file being compiled. Another useful one would be {current_binary} which maps to current file's binary(if successful).

**Comment by JulienKluge** [comment]
ahhh yessss this would makes sense ^^ 
I'll add it soon.
