### ISSUE TITLE
Scripting directories are not saved (reset after program restart)

### ISSUE THREAD

**Issue by RAYs3T** [JulienKluge/Spedit#103]
If you add a custom location to the script directories, the change is just saved for the current session.
If you close and reopen the program the scripting directories field is reset to default.

![image](https://user-images.githubusercontent.com/16596807/32400838-b7158d50-c105-11e7-88cd-2bcdb45ff5ba.png)

(After restarting the `include` directory disappears)

**This does not affect other fields like the copy directory.**

**Comment by JulienKluge** [comment]
As you already found out, its relative paths. Since we always look at them in top path, their not existing. Just use absolute ones.
