### ISSUE TITLE
Translations optimization

### ISSUE THREAD

**Issue by Arkarr** [JulienKluge/Spedit#115]
I saw your varible there, I couldn't resist.
Translation are now stored in a dictonary rather than in ONE SINGLE VARIABLE :anguished: !
Also, no need to create a new variable each time there is a new translation line.

**Comment by Arkarr** [comment]
Here are the changes I made because I don't have the rights (?) to push update.
[Spedit.zip](https://github.com/JulienKluge/Spedit/files/2058947/Spedit.zip)

**Comment by JulienKluge** [comment]
Yearh, pushing is only allowed for me but you can make a branche, make your changes and do a pull request. I'd happily insert it that way.

**Comment by Arkarr** [comment]
Will do, nice to see that you are still working on this !

**Comment by Arkarr** [comment]
I can not do a new branch, I'm not allowed to.

**Comment by Bara** [comment]
@Arkarr Fork this repo and create a new branch on your repo. This should work :o

**Comment by Arkarr** [comment]
@Bara  Silly me, it's done. Sorry.
