### ISSUE TITLE
UTF-8 compliant

### ISSUE THREAD

**Issue by kossolax** [JulienKluge/Spedit#16]
Hey,
 UTF-8 encoding is showed in ANSI. 
Ã© -> é Ãª -> ê Ã  -> à

**Comment by JulienKluge** [comment]
it fully works for me? Can you give instructions to reproduce this? 
http://www.imageupload.co.uk/images/2015/03/08/UTF8SPEdittest.png

**Comment by kossolax** [comment]
http://i.gyazo.com/9ab95abfa6c549188aefe2e45d3d41b3.png
https://www.ts-x.eu/download/1673/a.sp

**Comment by JulienKluge** [comment]
okay well, thats strange: http://www.imageupload.co.uk/images/2015/03/08/UTF8SPEdittest2.png

however - i'll add a setting to enforce an endocding - that should be working then.

**Comment by JulienKluge** [comment]
I looked in the avalonEdit code and it's auto detecting which encoding is used.- So i'am really clueless why this happens..

**Comment by JulienKluge** [comment]
since noone answers anymore: closed!
