### ISSUE TITLE
FTP passwords are shown in clear text

### ISSUE THREAD

**Issue by Xerrion** [JulienKluge/Spedit#18]
FTP passwords or passwords in general shouldn't be shown or parsed in clear text.
![screenshot_1](https://cloud.githubusercontent.com/assets/1850632/6600272/f133c468-c80e-11e4-954e-990fdfa451cc.png)

**Comment by JulienKluge** [comment]
Solved. Commit f1697fd
Your passwords are now protected via Random generated unique Key (generated on first startup of editor) to an AES 128bit encryption.
