### ISSUE TITLE
Crash when compiling in one configuration and trying to complile in another configuration.

### ISSUE THREAD

**Issue by Xerrion** [JulienKluge/Spedit#19]
As the title, the crash happends  because I am trying to compile in 1.7 and fails (It's me who forget to switch) and then switching to 1.6.4, then it just crashes and there is no errorlog, I can post a windows crash log. But it's in danish.

**Comment by Xerrion** [comment]
Off-topic: I would be nice to be able to search(and replace) in every open file. And maybe a better way to show project files.

**Comment by JulienKluge** [comment]
Do you use one of the release Beta files or did you compiled it by yourself? Because that sounds like a bug i already fixed (it has nothing to do with the config btw. - more with the failed compilation). 

For your offtopic: The search is planned and for the second: no - its an editor not an ide.

**Comment by Xerrion** [comment]
I use the beta 4.

For the off-topic: Sublime text and Brackets (Former Adobe Edge Code CC) are editors, and has that feature, but if you don't want that feature. I respect it.

**Comment by JulienKluge** [comment]
Yes, the bug is not fixed in it. It wil be in the 5th which i will release today i think. ^^

You know, i want that feature, but not now. Its something which belongs (in my opinion) in an IDE and spedit is not an ide.
