### ISSUE TITLE
Request custom properties.

### ISSUE THREAD

**Issue by WildCard65** [JulienKluge/Spedit#2]
Can you add a feature to SPEdit that if the file it's compiling a comment that reads exactly like an option(in a file) it runs a special script after compiling?

**Comment by WildCard65** [comment]
Eg:  
In plugin source: //FF2 Subplugin  
in config file: "FF2 Subplugin": "handle_ff2subplugin.bat"

**Comment by JulienKluge** [comment]
I don't make it for a particulary script but Issue #4 will take care of it for a customizable config.
