### ISSUE TITLE
Copy the .smx file doesn't working?

### ISSUE THREAD

**Issue by barel31** [JulienKluge/Spedit#20]
Hi,
First,  I'm sorry for my english
In the configuration the copy directory set to 'C:\Users*username*\Desktop'
But when I compile a plugin the .smx file created in the .sp directory...
Any reason why?

**Comment by JulienKluge** [comment]
because there is no auto-copy. Press F7 or select "Copy Plugins" int the Build-Menu

**Comment by barel31** [comment]
So why there is no auto-copy after compile?
And I can't change the default .smx files location?

**Comment by JulienKluge** [comment]
Because i think to press F7 after the compile is not that much work ^^ 
Sigh, that is the copy command for. When you want to have your smx in another directory, you'll copy it. To Compile the smx to another directory would be sensless and leads to confusion.

**Comment by barel31** [comment]
Okay, thank you for the answer and huge thanks for creating this amazing editor.
My new fav. editor from now. :)

**Comment by JulienKluge** [comment]
Thanks ^^
