### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by BAILANDO** [JulienKluge/Spedit#23]
Hello. Can you make hotkey for minize all modules? It will be very helpfull.

http://ctrlv.cz/FT8P <- screenshot

**Comment by ghost** [comment]
:+1: 
I think "Hotkey Manager" is planned.

**Comment by BAILANDO** [comment]
Ok, thanks :)

**Comment by JulienKluge** [comment]
this wont be part of the hotkey manager i think but when we are on this topic of collapse all foldings, which Hotkey-combination do you suggest?

**Comment by JulienKluge** [comment]
and btw. wee need two:
• collapse all
• expand all

**Comment by BAILANDO** [comment]
For example, CTRL-Keypad Minus and CTRL-Keypad Plus. And for another hotkey like in VS 2013, with SHIFT+Enter automatically jump on end of the line and make new line if you can add this

**Comment by BAILANDO** [comment]
Or without hotkey only make this option in topmenu, for example Tools section

**Comment by JulienKluge** [comment]
It'll surely get an Entry in the Menu yes. But the Hotkeys:
I don't think Ctrl+Plus (Minus) is appropriate since it would be better placed in the Fontsize-setting.
I tend To use something like:
Ctrl+P : Expand
Crtp+Shift(or alt)+P : Collapse

**Comment by BAILANDO** [comment]
Yes, Ctrl+P and Ctrl+Alt+P will be good.

**Comment by JulienKluge** [comment]
Its done with:
Ctrl+P: Expand
Ctrl+Shift+P: Collapse
