### ISSUE TITLE
enhanced intellisense

### ISSUE THREAD

**Issue by kossolax** [JulienKluge/Spedit#26]
Parsing Intellisense from current directory for auto completion, or via recursive includes checks, would be every helpful.

**Comment by JulienKluge** [comment]
An extract from the FAQ:

"...But this is not a function witch is supported by intention. So functions/constants are NOT added dynamicly."

Since it's not trivial to do: this is something for the far-far future. Planned but not in sight.
I'll leave this issue open to close it when i'll implement it.

**Comment by PremyslTalich** [comment]
Ciao,

In Notepad++ I was used to have a nice formated intellisense with highlighted function param hovered by caret. Can you please do that in Spedit? It would be very nice :-)

![what my Notepad++ looks like](http://ctrlv.cz/shots/2015/04/18/7bHK.png)

**Comment by JulienKluge** [comment]
Well its not a trivial task but something which can be done. 
But since i'm busying stuying i have no time to implement it. (i try to do it asap)

**Comment by JulienKluge** [comment]
Implemented and closed. It's not done via recursevly include-checks though.

**Comment by kossolax** [comment]
What about the correct autocompletion of methodmap ?

ArrayStack a = new ArrayStack(10);
a.Push(1);
delete a;

2016-03-26 16:34 GMT+01:00 Julien Kluge notifications@github.com:

**Comment by JulienKluge** [comment]
You mean, that SPEdit suggests only the Methods and Properties assigned to ArrayStack in this case? Well, I have to dissappoint you, again. Even the new condenser, does not saves enough context-informations to enable us to do that. It's not, that I couldn't write such things, but I do not have the time and motivation to. Sorry. But the suggestions of the methodmaps in the autocompletition will come.

**Comment by kossolax** [comment]
I understand, should I open a new ticket?

2016-03-26 16:46 GMT+01:00 Julien Kluge notifications@github.com:

**Comment by JulienKluge** [comment]
No. This isn't nessecary.
