### ISSUE TITLE
Lysis errors

### ISSUE THREAD

**Issue by WildCard65** [JulienKluge/Spedit#28]
Decompiling my freedom_abilities.ff2(compiled with spider.limetech.org) with SPEdit's lysis produces the following errors:  
Error while write Globals
Details: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
Stacktrace:    at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at Lysis.SourceBuilder.dumpArray(Int32 address, Int32 size)
   at Lysis.SourceBuilder.dumpArray(Variable var, Int32 address, Int32 level)
   at Lysis.SourceBuilder.writeGlobal(Variable var)
   at Lysis.SourceBuilder.writeGlobals()
   at Lysis.LysisDecompiler.Analyze(FileInfo fInfo)  
/\* ERROR! Unrecognized opcode genarray_z _/
 function "EmitSoundToAll" (number 14)  
/_ ERROR! Unrecognized opcode stradjust_pri _/
 function "CReplaceColorCodes" (number 19)  
/_ ERROR! Unable to cast object of type 'Lysis.LDebugBreak' to type 'Lysis.LConstant'. _/
 function "GetThisPluginName" (number 25)  
/_ ERROR! Unrecognized opcode neg */
 function "Do_TruePower" (number 36)

**Comment by WildCard65** [comment]
To compare this project's lysis with god-tony's:  
/\* ERROR! java.lang.NullPointerException _/
 function "GetThisPluginName" (number 25)  
/_ ERROR! java.lang.ClassCastException: lysis.nodes.types.DTempName cannot be cast to lysis.nodes.types.DDeclareLocal */
 function "SpawnWeapon" (number 57)

**Comment by JulienKluge** [comment]
I can perhaps fix the bug with the error while writing the globals but not the other ones. 
I feal not really responsibel for Lysis. I've integrated it into Spedit and fixed itas good as possible without even knowig what it realy does. So I want fix the errors. 
Sou should post this errors in the Lysis Repository (even if it's highly unlikely that it'll be fixed.).

**Comment by WildCard65** [comment]
ok, error with GetThisPluginName is caused by the following: for (;;)

**Comment by JulienKluge** [comment]
can i get a crashing smx for this?

**Comment by WildCard65** [comment]
my ff2 subplugin is what caused the lysis errors,

**Comment by JulienKluge** [comment]
link?

**Comment by WildCard65** [comment]
https://www.dropbox.com/s/9uohnmh2tk72w6k/serpentine.zip?dl=0

**Comment by JulienKluge** [comment]
fixed
