### ISSUE TITLE
Another feature request.

### ISSUE THREAD

**Issue by WildCard65** [JulienKluge/Spedit#29]
To go with #27 this feature request will help out users of this program.  
First: specify the compiled binary file extension(default: smx)

**Comment by JulienKluge** [comment]
Why do we need this?

**Comment by WildCard65** [comment]
FF2 subplugins use .ff2

**Comment by JulienKluge** [comment]
3 questions:
You compile to ff2 from sp? 
You can rename smx to ff2?
Does fullfill the extension any specified task?

**Comment by WildCard65** [comment]
It'll make compiling ff2 subplugins easier if spcomp does the saving to .ff2 instead of .smx no need of using rm to delete old file then ren to new name.

**Comment by WildCard65** [comment]
Also to add onto it, the rcon {plugin_reload} alias only supports smx let alone support for subfolders like FF2's freaks folder.

**Comment by JulienKluge** [comment]
So as far as I investigated it, *.ff2 is just an ending, from one plugin which break intentionally the standard conventions without any plausible reason just to be unique?! 
I wont support that. Everyone who thinks to follow this can use the commandline. It's made for such tasks. 
Sorry I'm rude to that topic but I just don't like breaking standard conventions without any real reason.

**Comment by WildCard65** [comment]
Then add an alias to the rcon thing just for the plugin's file name(minus
the .smx)?

**Comment by JulienKluge** [comment]
thats difficult since this abbreviation is capable of handling mutiple files. 
But I'am wondering if sm will accept the commands without the file extensions?

**Comment by WildCard65** [comment]
Yes, SM accepts plugin names without extensions. It will by default add the
.smx to the filename if not found.

**Comment by JulienKluge** [comment]
Yep. Than i think i wont implement this as long as their is no important reason or support from sourcemod itself. Sorry.

**Comment by WildCard65** [comment]
Sourcemod supports loading plugins with just file name(eg: basecomms), example: sm plugins load basebans  
SM will do the following:  
1) Try to find file named: basebans  
2a) If found, load it as a plugin.
2b) If not found, try finding basebans.smx  
3a) If 2b ran and basebans.smx exists, load it as plugin.
3b) If 2b ran and basebans.smx not found, report error.

**Comment by JulienKluge** [comment]
Implemented the compromise on not sending the extensions.

**Comment by WildCard65** [comment]
k thx
