### ISSUE TITLE
Request: Tree View.

### ISSUE THREAD

**Issue by Xerrion** [JulienKluge/Spedit#31]
I would really like to see a tree view in addition to the open tabs for better navigation when I have alot of files open at a time. (Which I have most of the time). Also GitHub integration would be a nice feature.

**Comment by ghost** [comment]
I think general git support is better than only github.

**Comment by JulienKluge** [comment]
Will not come in SPEdit_v1, sry ;D

**Comment by JulienKluge** [comment]
Well, I know i said this wont come in v1_... but currently I think this is a goord addition for the editor.
