### ISSUE TITLE
Suggest feature

### ISSUE THREAD

**Issue by DarklSide** [JulienKluge/Spedit#32]
Russian:
В данной случае, при выделении функции (точнее её часть) - выделяется другой найденный часть функции. Мое предложение добавить пункт, чтобы выделялись только целое слово, а нее её чаcть.
Например есть слова:
a. RoundStart
b. RoundStartandEnd

При выделении "RoundStart" -> выделяется и из b. "RoundStart"andEnd.
Т.е. дабавить опцию выделять только целые слова.

English (google translate):
In this case, the allocation of functions (or rather part of it) - is allocated another part of the function found. My suggestion is to add a paragraph to highlight a whole word only, but it it PART OF.
For example there are words:
a. RoundStart
b. RoundStartandEnd

When you select "RoundStart" -> stands out from b. "RoundStart" andEnd.
Ie mount a option to select only whole words.

**Comment by JulienKluge** [comment]
I have actually no clue what he is asking.
Can anyone with russian experience translate it for me?

**Comment by JulienKluge** [comment]
Well, roughly one year after submitting this suggesting, I gopt waht you wanted to say aaaand: no. sorry :D
