### ISSUE TITLE
Another lysis error.

### ISSUE THREAD

**Issue by WildCard65** [JulienKluge/Spedit#34]
Edit: Woops hit enter too early.

```
public void OnPluginStart()
{

/* ERROR! unknown load */
 function "OnPluginStart" (number 3)
```

Cause:

``` sourcepawn
public void OnPluginStart()
{
    FF2BossInfo info;
    PrintToServer("%d", info.ClassIndex);
}
```

FF2BossInfo is a method map for a rewrite from sratch I want to do for ff2 v2, the methodmap is defined in a sp file included into compiled one.

**Comment by ghost** [comment]
https://github.com/peace-maker/lysis-java
This can help you. @TheJelle

**Comment by JulienKluge** [comment]
I don't really want to support Lysis any longer. I leave the current state as it is. But I think, sourcemod will go through much of cahnge the next time. Im sorry.
