### ISSUE TITLE
[Feature Request] Save as you type?

### ISSUE THREAD

**Issue by sm9cc** [JulienKluge/Spedit#41]
Hello everyone, nowadays I feel that saving as you type should be a standard feature in IDE software, 
Google docs does this for example, although its not an IDE its definitely possible and I feel an option to maybe turn this feature on or off would be a good idea if it was added.

Cheers.

**Comment by JulienKluge** [comment]
I cannot really feel warm with that. I for myself would hate it. I could think about a autosaving with dynamic adjustable saving times.

**Comment by CanadianJeff** [comment]
that would make it really hard on disk I/O lowering its lifespan constantly making writes like that maybe if it autosaved every XX min would be better
