### ISSUE TITLE
SPedit crashes

### ISSUE THREAD

**Issue by Hackmastr** [JulienKluge/Spedit#42]
It crashes when opening a file through browser, then hitting ctrl + s.

Reproduce: Download some .sp from Alliedmods, click(using your browser) on it*, once opened in SPedit, hit CTRL + S > boom, SPedit crash.

You must have SPedit as default .sp file editor.

**Comment by JulienKluge** [comment]
I cannot reproduce this. This also shouldn't happen with the newer versions. Please Check (Tools->Check for Updates), if you have the newest version running.

**Comment by Hackmastr** [comment]
It's up to date :)

**Comment by JulienKluge** [comment]
Does this also happens when you do File->Save ?

**Comment by JulienKluge** [comment]
does this also happen with the new version?

**Comment by Hackmastr** [comment]
@JulienKluge will update and tell You

**Comment by Hackmastr** [comment]
@JulienKluge Great! No more crashes! Thanks!

**Comment by JulienKluge** [comment]
Cool ^^
