### ISSUE TITLE
[Idea] AutoClose brackets/quotes/chars.

### ISSUE THREAD

**Issue by benjaminforras** [JulienKluge/Spedit#49]
If I type '{' it closes it with '}'. So with as '[' and ']'
Also It could be disabled in the Options menu.

**Comment by Bara** [comment]
Same for " please

**Comment by benjaminforras** [comment]
Well, if you add that, add this too: **'** :)

**Comment by meev** [comment]
This should be all of the autocloseable chars: ', ", <, (, {, [ 
all tho < is used in statements without the closing part so you might wanna exclude < unless you got something that can filter it.

**Comment by JulienKluge** [comment]
"<" should not be an autoclosable char. There would be ways to detect this, but i would prefer not to have such inconsistent handling with them.
" and ' can not be implemented as fast as the brackets (there is much more to keep attention to) but i'll do it in the future i think.

**Comment by not1ce111** [comment]
Can you make settings for disable this?

**Comment by JulienKluge** [comment]
There is already a setting.
