### ISSUE TITLE
Global variables not in auto-complete/intelisense

### ISSUE THREAD

**Issue by TnTSCS** [JulienKluge/Spedit#5]
If I create a global variable:

char MyString[80];

If I try to work with that in the plugin, it will not list it in the auto-complete pop-up.  Not sure if this is on the road map to add as a feature, but it would be a nice one to have.

**Comment by JulienKluge** [comment]
Did you created iot in the include files or in your Plugin ?

**Comment by TnTSCS** [comment]
In my plugin.

**Comment by JulienKluge** [comment]
The Editor does not provide the ability of Life Source analyzing. This is also a feature which isn't planned yet out of several reasons. If I make the Editor ever to an IDE, then this will be implemented. But not know. Sry.
