### ISSUE TITLE
Close button and the Close All button don't work.

### ISSUE THREAD

**Issue by oaaron99** [JulienKluge/Spedit#53]
Close button and the Close All button don't work.

Also CTRL+W doesn't work to close the file either.

https://gfycat.com/DescriptiveGeneralHairstreakbutterfly

**Comment by Bara** [comment]
Now I've problems with the close button(s).

**Comment by JulienKluge** [comment]
which problems do you have?

**Comment by Bara** [comment]
I can't close files like "hosties3.sp" but other files like "ttt_wallhack.sp" or "ttt.sp" works fine.

**Comment by oaaron99** [comment]
Doesn't seem to be a number issue. Maybe size of the file??

**Comment by Bara** [comment]
hosties3 has a size ~200kb (with all .sp-includes) and ttt ~110kb (with all .sp-includes).

But today it works fine... weird
