### ISSUE TITLE
[Feature Request] Edit Templates

### ISSUE THREAD

**Issue by oaaron99** [JulienKluge/Spedit#55]
It would be cool if we could edit and save plugin templates in addition to the default ones. It would save a lot of time and help because not everyone structures their plugins the same.

**Comment by JulienKluge** [comment]
you can. The Editor simply does not give you a gui to do it.
you can go to the installation directory of the program (if you installed it, then %appdata%/spedit) 
go to sourcemod/templates
and you'll see all templates there and a xml file which controls everything. 
the structure of the xml is straightforward so you can add your own templates or delete old ones.

**Comment by oaaron99** [comment]
Ah cool, I never really played around with it so I didn't know. Thanks for the information.
