### ISSUE TITLE
Lysis Error

### ISSUE THREAD

**Issue by oaaron99** [JulienKluge/Spedit#59]
Error while loading file.
Details: Index and count must refer to a location within the buffer.
Parameter name: bytes
Stacktrace:    at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at SourcePawn.SourcePawnFile..ctor(Byte[] binary)
   at Lysis.PawnFile.FromFile(String path)
   at Lysis.LysisDecompiler.Analyze(FileInfo fInfo)

**Comment by JulienKluge** [comment]
i'll look into it. But don't expect this to change. Lysis got older and with the new opcodes & ... it does not really work anymore very well. I also plan to drop it from SPEdit. Anywhere in the web there is a free decompiler based on Java though.
