### ISSUE TITLE
Deutsche Übersetzung

### ISSUE THREAD

**Issue by Bara** [JulienKluge/Spedit#63]
Es fehlen ein paar deutsche Übersetzungen wie:
https://github.com/JulienKluge/Spedit/blob/master/Resources/lang_0_spedit.xml#L23
https://github.com/JulienKluge/Spedit/blob/master/Resources/lang_0_spedit.xml#L26
https://github.com/JulienKluge/Spedit/blob/master/Resources/lang_0_spedit.xml#L36-L37

**Comment by JulienKluge** [comment]
Du es fehlen noch ewig viele :D 
Ich bin im Implementierungsprozess. Das wird alles wachsen und wachsen ^^ 
Ich mach das mal zu. Du kannst das ja wieder öffnen wenn ich im Ende wirklich was vergessen habe ;)
