### ISSUE TITLE
Stop compile-process

### ISSUE THREAD

**Issue by Bara** [JulienKluge/Spedit#64]
Hab gerade keine Lust auf englisch (keine Zeit):
Wenn ich mehrere sp-Dateien auf habe und ausversehen auf F5 komme statt F6, dann versucht der alles zu compilen und durch die include smlib kann es manchmal ewig dauern (und das für nichts).

Mein Vorschlag: Es mit ESC abbrechen zu können.

**Comment by JulienKluge** [comment]
Sollte nicht zu schwierig sein. Mach ich dann morgen oder so.
