### ISSUE TITLE
[Request] Select which .sp to compile

### ISSUE THREAD

**Issue by Phil25** [JulienKluge/Spedit#76]
Hello, I was wondering if you could add something like in the title.

It would be really useful when working on larger plugins which are split into multiple files. That way you don't have to switch tabs to compile when working on an include.

**Comment by WildCard65** [comment]
That is already available in SPEdit, not in way you expect it to.

In bottom left corner of SPEdit window, there is check box beside "compile", unchecked, "Compile All" will not compile it, default is checked for .sp files, unchecked for .inc files.

**Comment by JulienKluge** [comment]
This is indeed already implemented like WildCard specified. 
Are you meaning this?

**Comment by Phil25** [comment]
Yes, WildCard's suggestion would work, I totally forgot about that feature. I was thinking in the back of my head about being able to set the .sp to compile for your current session or something like that.
