### ISSUE TITLE
NULL_VECTOR highlighting broken

### ISSUE THREAD

**Issue by WildCard65** [JulienKluge/Spedit#78]
It seems NULL_VECTOR isn't being highlighted on latest release.

**Comment by JulienKluge** [comment]
I looked into it. NULL_Vector is defined in core.inc as:
"public float NULL_VECTOR[3];"
The Sourcepawn-Parser does not parse non-constants. And ignores them. You could try to change it to:
"public const float NULL_VECTOR[3];"
This should reenable the highlighting.
