### ISSUE TITLE
Add checkbox for using hardware encryption on specific configs

### ISSUE THREAD

**Issue by fakuivan** [JulienKluge/Spedit#82]
The last update broke my setup. I had my configs syched using an encrypted seafile library and I could just do F6, F8 F10 from any PC to compile, upload and reload my plugins on my test server. A checkbox for turing this on/off would be great, thanks for reading :D.

**Comment by JulienKluge** [comment]
Well. Just start SPEdit with the "-rcck" Argument, close it, and resync the new options_0.dat. It should work again (after you redid your passwords in the config and resynced them) ;)

**Comment by fakuivan** [comment]
I don't have any problems if I only work from one pc, the problem is that
if I move to a different one, the passwords are not decrypted correctly.

2017-02-05 10:03 GMT-03:00 Julien Kluge <notifications@github.com>:
