### ISSUE TITLE
can you add Chinese language

### ISSUE THREAD

**Issue by kitaynoctis** [JulienKluge/Spedit#84]
can you add chinese language？pls，thx ：)

**Comment by JulienKluge** [comment]
Can you provide me the translations?

**Comment by JulienKluge** [comment]
really, I don't speak it. If you want to have it, someone has to translate it.

**Comment by dev-xiamu** [comment]
yes，i can😀

2017-04-20 5:33 GMT+08:00 Julien Kluge <notifications@github.com>:

**Comment by kitaynoctis** [comment]
yes. i can translations. give me some time
and,can you provide the English text for me？

**Comment by Reinakumiko** [comment]
我已经把那些翻译了... 你可以从pull里下下来到本地用?

**Comment by kitaynoctis** [comment]
@Reinakumiko 啊哈？good job 。。那没我什么事了，233

**Comment by Reinakumiko** [comment]
_(:з」∠)_  你也可以帮我修正一下 
还有些地方不能改参数位置 好烦


现在的话也只能自己去下下来丢到程序里了吧
下一次更新大概是一个月之后了23333

**Comment by kitaynoctis** [comment]
@Reinakumiko 你翻译得很不错了。只是有些感觉不够简洁，比如“文件另存为”，换成“另存为”是不是更简洁些呢。。。
另外，不会玩GitHub

**Comment by Reinakumiko** [comment]
@dev-xiamu 我也不太会啊 都差不多 
那里面有些翻译是我记忆力程序用过的
嘛不过这个没啥 其他的看使用情况吧...

**Comment by kitaynoctis** [comment]
@Reinakumiko 加一波steam好友？？不介意的话.....

**Comment by Reinakumiko** [comment]
@dev-xiamu 之前回去忘了... 
http://steamcommunity.com/id/reinakumiko
这个是我Steam的社区连接

**Comment by JulienKluge** [comment]
the translations got added and you both are now listed as contributors
https://github.com/JulienKluge/Spedit/commit/01495daea531968b00ceae593418f2af2f604331

Thank you and changes can be made with a pull request. I also added the additional parameter in the ReplacedOffset translation unit.
