### ISSUE TITLE
"Fake" crash & crash with closing non-saved tabs.

### ISSUE THREAD

**Issue by Hexer10** [JulienKluge/Spedit#91]
If I do somethink like this:
`#define Test "0.00"

public void OnSomeThink()
{
	Test = 5;
} `

( I know that should'nt be done)

the  editor start crashing,  I get the crash popup but when i actually click cancel it doens't crash.

and when I close a non saved tag all the editor crashed and I need to kill the process.

**Comment by Bara** [comment]
It's a fail from the compiler and not from spedit. @psychonic 

You could create a issue here https://github.com/alliedmodders/sourcemod/issues

**Comment by psychonic** [comment]
If it's an issue with the compiler, it belongs on the alliedmodders/sourcepawn project. Go ahead and file there though. I don't really deal with SP internals much.

**Comment by Hexer10** [comment]
Thanks both, I didn't know that; since I use spedit I've never used the compiler alone.
